### ISSUE TITLE
Typo in Explanation

### ISSUE THREAD

**Issue by pcalebho** [JamesNewton/AdvancedRoboticsWithJavascript#1]
So if you set x to 1 write a function to add 10 to x, and another function to multiply x time 20, then you call both of them you can't really know if the result will be 220 or 21. ( (1+10)20 or 120+10 ).

If I'm understanding this correctly, we don't know whether the first or second function will execute first. If that's the case, it should be 220 or 30 ( (1+10)20 or (1*20)+10 ).

**Comment by JamesNewton** [comment]
Excellent catch! Thank you!
