### ISSUE TITLE
The first high-level programming language

### ISSUE THREAD

**Issue by Dinomasater186** [JamesNewton/AdvancedRoboticsWithJavascript#8]
Plankalkül wast the first high-level programming language.

**Comment by JamesNewton** [comment]
Excellent point, and true. And Konrad Zuse deserves a lot more mention than he gets. 
https://en.wikipedia.org/wiki/Konrad_Zuse
However, it was not implemented and remained a design on paper only. Fortran was the first high level language to have a functional implementation, as opposed to just a design on paper. 

Early mechanical computers like the Z1 blur the lines between robot and computer. In fact, there is an excellent example of mechanical computing related to Dexter. Remind me to mention Zuse, Plankalkül, and modern mechanical computing when we take a break tomorrow.
